# Generated by Django 3.1 on 2020-12-13 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201213_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='N_tarjeta',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
