# Generated by Django 3.1 on 2020-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200910_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
