# Generated by Django 3.1 on 2020-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200922_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
