# Generated by Django 3.1 on 2020-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200922_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
