# Generated by Django 3.1 on 2020-10-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200923_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arriendo_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reserva_activa',
            field=models.BooleanField(default=False),
        ),
    ]
