# Generated by Django 3.1 on 2020-09-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('banos', models.PositiveIntegerField(null=True, verbose_name='baños')),
                ('dormitorios', models.PositiveIntegerField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('estado_mantencion', models.BooleanField(blank=True, default=False, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='departamentos_principal/%Y/%m')),
                ('mantencion', models.DateField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(null=True)),
                ('metros_cuadrados', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioDepartamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Buen estado', 'Buen estado'), ('Mal estado', 'Mal estado')], default='Buen estado', max_length=20, null=True)),
                ('precio', models.PositiveIntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_inventario', to='departamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='departamentos/%Y/%m')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_imagenes', to='departamentos.departamento')),
            ],
        ),
    ]
