# Generated by Django 3.1 on 2020-08-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('baños', models.PositiveIntegerField(null=True)),
                ('dormitorios', models.PositiveIntegerField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('estado_mantencion', models.BooleanField(blank=True, default=False, null=True)),
                ('mantencion', models.DateField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(null=True)),
                ('metros_cuadrados', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='departamentos/%Y/%m')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_imagenes', to='departamentos.departamento')),
            ],
        ),
    ]
