# Generated by Django 3.1 on 2020-09-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagenesDepartamento',
            new_name='Imagen',
        ),
        migrations.RenameModel(
            old_name='InventarioDepartamentos',
            new_name='Inventario',
        ),
    ]
