# Generated by Django 3.1 on 2020-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='departamentos_principal/%Y/%m'),
        ),
    ]
