# Generated by Django 3.1 on 2020-10-13 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20201010_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='banos',
            field=models.PositiveIntegerField(default=1, verbose_name='baños'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='dormitorios',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='metros_cuadrados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='acompanantes',
            field=models.PositiveIntegerField(default=0, verbose_name='acompañantes'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dia',
            field=models.CharField(default=datetime.date(2020, 10, 13), max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='conductor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='vehiculo',
            field=models.CharField(max_length=50),
        ),
    ]
