# Generated by Django 3.1 on 2020-09-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20200904_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='departamentos.departamento'),
        ),
    ]
