# Generated by Django 3.1 on 2020-08-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='baños',
            new_name='banos',
        ),
    ]
