# Generated by Django 3.1 on 2020-09-05 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0003_auto_20200904_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado_mantencion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.PositiveIntegerField(verbose_name='días')),
                ('abono', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to='departamentos.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
