# Generated by Django 3.1 on 2020-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20200831_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='banos',
            field=models.PositiveIntegerField(null=True, verbose_name='baños'),
        ),
    ]
