# Generated by Django 3.1 on 2020-10-16 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_auto_20201014_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='dia',
            field=models.CharField(default=datetime.date(2020, 10, 16), max_length=50),
        ),
    ]
