# Generated by Django 3.1 on 2020-09-05 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0004_auto_20200904_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='departamento',
            new_name='reserva',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='abono',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='total',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='diferencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_llegada', models.DateField(blank=True, null=True)),
                ('abono', models.PositiveIntegerField()),
                ('dias_estadia', models.PositiveIntegerField(verbose_name='días_estadia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='departamentos.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
