# Generated by Django 3.1 on 2020-09-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_auto_20200831_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdepartamento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='departamentos/%Y/%m'),
        ),
        migrations.CreateModel(
            name='InventarioDepartamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Buen estado', 'Buena estado'), ('Mal estado', 'Mal estado')], default='Buen estado', max_length=20, null=True)),
                ('precio', models.PositiveIntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_inventario', to='departamentos.departamento')),
            ],
        ),
    ]
