# Generated by Django 3.1 on 2020-10-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0005_auto_20201016_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='titulo',
        ),
    ]
