# Generated by Django 3.1 on 2020-10-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_remove_departamento_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='descripcion',
        ),
    ]
