# Generated by Django 3.1 on 2020-09-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_auto_20200905_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dias_estadia',
            field=models.PositiveIntegerField(verbose_name='días estadia'),
        ),
    ]
