# Generated by Django 3.1 on 2020-09-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0007_auto_20200906_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
