# Generated by Django 3.1 on 2020-10-19 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_auto_20201017_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='dia',
            field=models.CharField(default=datetime.date(2020, 10, 18), max_length=50),
        ),
    ]
