# Generated by Django 3.1 on 2020-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_arriendo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='acompanantes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
