# Generated by Django 3.1 on 2020-09-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0009_reserva_acompanantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='acompanantes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='acompañantes'),
        ),
    ]
