# Generated by Django 3.1 on 2020-09-13 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0013_reserva_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
