# Generated by Django 3.1 on 2020-09-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0014_auto_20200912_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_verificado', models.BooleanField(default=False)),
                ('desde', models.CharField(max_length=50)),
                ('hacia', models.CharField(max_length=50)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='departamentos.reserva')),
            ],
        ),
    ]
