# Generated by Django 3.1 on 2020-09-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0015_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='departamentos.reserva'),
        ),
    ]
