# Generated by Django 3.1 on 2020-09-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0016_auto_20200916_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='estado_verificado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
