# Generated by Django 3.1 on 2020-09-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0018_transporte_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
