# Generated by Django 3.1 on 2020-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0019_auto_20200919_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
