# Generated by Django 3.1 on 2020-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0021_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
