# Generated by Django 3.1 on 2020-09-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0022_auto_20200924_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='departamentos.reserva'),
        ),
    ]
