# Generated by Django 3.1 on 2020-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0023_auto_20200925_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tour',
            name='dia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
