# Generated by Django 3.1 on 2020-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0024_auto_20200926_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
