# Generated by Django 3.1 on 2020-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0025_tour_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='llegada',
            field=models.BooleanField(default=False),
        ),
    ]
