# Generated by Django 3.1 on 2020-10-02 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0026_reserva_llegada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='departamentos.arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='departamentos.arriendo')),
            ],
        ),
    ]
