# Generated by Django 3.1 on 2020-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0027_check_in_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='precio',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
