# Generated by Django 3.1 on 2020-10-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0028_transporte_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='reserva',
        ),
        migrations.AddField(
            model_name='tour',
            name='reserva',
            field=models.ManyToManyField(blank=True, related_name='tour', to='departamentos.Reserva'),
        ),
    ]
