# Generated by Django 3.1 on 2020-10-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0030_auto_20201005_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='arriendo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='departamentos.arriendo'),
        ),
        migrations.AlterField(
            model_name='check_out',
            name='arriendo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='departamentos.arriendo'),
        ),
        migrations.AlterField(
            model_name='check_out',
            name='valor_danos',
            field=models.PositiveIntegerField(verbose_name='Valor daños'),
        ),
    ]
