# Generated by Django 3.1 on 2020-10-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0031_auto_20201005_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to='departamentos.reserva'),
        ),
    ]
