# Generated by Django 3.1 on 2020-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0032_auto_20201009_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], max_length=20, null=True),
        ),
    ]
